### ISSUE TITLE
Translations not included in generated CSV

### ISSUE THREAD

**Issue by jpalo** [estruyf/vscode-spfx-localization#1]
After doing "SPFx export locale labels to CSV", the generated CSV is missing the actual translations. Using 1.2.2 of your tool and VSCode 1.32.3. What could be causing this?

Output
```
key;Locale en-us;Locale fi-fi;projectFoldersStrings
UIPropsGroupCommon;;;x
```

Input fi-fi.js
```
define([], function() {
  return {        
    UIPropsGroupCommon: "Yleiset asetukset"
  }
});
```

Input en-us.js
```
define([], function() {
  return {    
    UIPropsGroupCommon: "Common settings"
  }
});
```
mystrings.d.ts
```
declare interface IProjectFoldersStrings {
  UIPropsGroupCommon: string;
}

declare module 'projectFoldersStrings' {
  const strings: IProjectFoldersStrings;
  export = strings;
}
```

**Comment by estruyf** [comment]
That's weird, tried the same thing on my end and can't seem to reproduce it. Can you try be removing the CSV file and recreating it again?

What does you project structure look like?

**Comment by WuWei42** [comment]
I have the same wrong result. Only keys were exported.
Here is my structure:
![image](https://user-images.githubusercontent.com/37153965/62183584-0f346a80-b35b-11e9-9b0d-4efde2951240.png)

**Comment by estruyf** [comment]
@WuWei42 can you provide me some samples of your loc JS files?

**Comment by estruyf** [comment]
Think I found the thing that could cause this issue, although I'm not sure, as I'm still unable to reproduce it. Some changes have been implemented and a new version has been released (1.3.0).

@jpalo @WuWei42 would both of you be able to test it out to see if it fixes the issue?

**Comment by jpalo** [comment]
Can no longer reproduce the problem, thank you!

**Comment by estruyf** [comment]
Thank @jpalo for verifying

**Comment by WuWei42** [comment]
Thands for the fix. 
Now it is a usefull tool. Thanks for that.
I recommend to delete the old ressource files after creation the CSV and use your extension to create the resource files again. 

Here another usefull extension which works very well with your ex: https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv
