### ISSUE TITLE
Feature request: comments for CSV translations

### ISSUE THREAD

**Issue by nbelyh** [estruyf/vscode-spfx-localization#11]
Would be great to have one more column in CSV "comment".

In real project, it's often very useful to have comments  for translated strings. This can be "please review", "needs improvment", "not used", "used in placx XYZ", etc. Most translation/localization tools support this functionality. Lingobit, ResX Translator, etc.
Also, can be used to mark "not yet translated" strings for example.

**Comment by estruyf** [comment]
Actually a great idea, we have this as well in our own localization system.

**Comment by estruyf** [comment]
@nbelyh merged your PR + separated the `timestamp` to its own column. This is now available in version `1.7.0`.
