### ISSUE TITLE
Sort all strings (in particular, strings.d.ts) according to the CSV (alphabetically)

### ISSUE THREAD

**Issue by nbelyh** [estruyf/vscode-spfx-localization#12]
Now when you add a new string, it is added to the beginning of the file in strings.d.ts, but in the middle in .js files when you generate. But when you generate it is added according to the CSV order. So it's a bit messy.

It would be great to have consistency here, so that the extension always follows the same when adding strings.
Otherwise, this produced a lot of "noise" if you check the difference with the previous version afterwards.

**Comment by estruyf** [comment]
That is a great enhancement! Would you be willing to create a PR for it?

**Comment by nbelyh** [comment]
If I have time, will do :)

**Comment by estruyf** [comment]
Just released version `1.6.0` of the extension. Thanks @nbelyh!
