### ISSUE TITLE
Export csv file include unwanted spaces

### ISSUE THREAD

**Issue by stevebeauge** [estruyf/vscode-spfx-localization#24]
When I export to CSV, the coding style does not trim spaces.

For example, let's say  I have this strings:

````
define([], function () {
    return {
        MyStringWithASpace : "my value 1",
        MyString: "my value 2"
    };
});
````

Leads to : 

````
key;Locale en-us;Locale fr-fr;LocalizeTestWebPartStrings;Comment;Timestamp
MyString;;my value 2;x;;2022-03-16T21:38:36
MyStringWithASpace ;;my value 1;x;;2022-03-16T21:38:36
````

As you can, the exported key includes a space behind the name from the locale module.

It's worse if multiple locale files has not exactly the same format, it can leads to two rows in the CSV file:

````
key;Locale en-us;Locale fr-fr;LocalizeTestWebPartStrings;Comment;Timestamp
MyString;my value 2;my value 2;x;;2022-03-16T21:42:12
MyStringWithASpace;my value 1;;x;;2022-03-16T21:42:12
MyStringWithASpace  ;;my value 1;x;;2022-03-16T21:42:30
````

This is also true in the other way. Importing a CSV file that includes such spaces generate differents keys:

Literally (spaces are exactly these ones) : 

````
declare interface ILocalizeTestWebPartStrings {
    MyString: string;
    MyStringWithASpace: string;
MyStringWithASpace  : string;
}
````

**Comment by nbelyh** [comment]
@stevebeauge the above PR should fix the issue, it's really a minor one.
