### ISSUE TITLE
Excel format support

### ISSUE THREAD

**Issue by nbelyh** [estruyf/vscode-spfx-localization#26]
After using the extension for a couple of years, I'd like to improve it by adding Excel format support.
Basically, it's just about an optional change of CSV => XLSX.

In Excel file, you can set width, colors, add comments to rows, etc, that is not possible with CSV, you have to resize the columns every time you edit.

As the next step, integration with some online list could be good.

![image](https://user-images.githubusercontent.com/528366/208999602-d2171f9c-8e07-4240-9cc4-d6400bd1c560.png)

I'm adding a PR to support Excel format.
To activate, just change in the extension of the file in the settings:

![image](https://user-images.githubusercontent.com/528366/208999806-b36ea7b2-8bcc-4524-86bb-6b1458b02bf7.png)

@estruyf would appreciate if you could look at this 😄

**Comment by estruyf** [comment]
This is now supported in version `1.9.0`. Thanks @nbelyh for this implementation! Great work.
