### ISSUE TITLE
Updating MyStrings.d.ts when importing CSV

### ISSUE THREAD

**Issue by nbelyh** [estruyf/vscode-spfx-localization#6]
Environment: React + Typescript.

Now if you import a CSV file (run a command to import), the string "definition" typescript file is not updated. 
Means, if there are new keys added to CSV, they are not added to MyStrings.d.ts file (i.e. only the JavaScript files are updated).

Is it expected to work this way (why?) or it is just a missing feature?

**Comment by estruyf** [comment]
Thank you @nbelyh for the PR. This is now merged and will be available for update in a couple of minutes.
