### ISSUE TITLE
CSV UTF8 BOM marker option

### ISSUE THREAD

**Issue by nbelyh** [estruyf/vscode-spfx-localization#8]
It would be nice to have a BOM marker option added. Now if you double-click the CSV file, Excel on Windows does not open it properly if the file contains non-ASCII UTF8 characters. So you may need to open it in Excel by specifically selecting UTF8 encoding.

What is BOM: https://en.wikipedia.org/wiki/Byte_order_mark

So an option in the extension settings could be great.
Will see if I could add this myself if yes then probably will come up with a PR :)

**Comment by nbelyh** [comment]
Created related PR

**Comment by estruyf** [comment]
This has now been merged and available in version `1.5.0`.
